<?php
$displayName = trim((string) ($user['first_name'] ?? '') . ' ' . (string) ($user['last_name'] ?? '')) ?: $user['username'];
$userInitials = trim(mb_substr(trim((string) ($user['first_name'] ?? '')), 0, 1)
    . mb_substr(trim((string) ($user['last_name'] ?? '')), 0, 1));
$userInitials = strtoupper($userInitials !== '' ? $userInitials : mb_substr($displayName, 0, 2));
$totpSetupSecret = $_SESSION['totp_setup_secret'] ?? null;
$totpEnabled = !empty($user['totp_enabled_at']);
$totpPolicyStatement = Database::connection()->prepare('SELECT totp_policy FROM club WHERE id = :club_id');
$totpPolicyStatement->execute(['club_id' => $user['club_id']]);
$totpPolicy = $totpPolicyStatement->fetchColumn() ?: 'OPTIONAL';
$totpRequired = $totpPolicy === 'REQUIRED';
$totpProvisioningUri = is_string($totpSetupSecret)
    ? (new TotpService())->provisioningUri($totpSetupSecret, (string) ($user['email'] ?: $user['username']))
    : null;
?>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>My account · CAT</title><link rel="stylesheet" href="<?= e(asset('app.css')) ?>"><?php if (in_array($user['role_code'], ['ADMINISTRATOR', 'REGISTRAR'], true)): ?><script src="<?= e(asset('site-nav.js')) ?>" defer></script><?php endif; ?><?php if (is_array($coachNavigator)): ?><link rel="stylesheet" href="<?= e(asset('coach-navigator.css')) ?>"><script src="<?= e(asset('coach-navigator.js')) ?>" defer></script><?php endif; ?><?php if ($totpProvisioningUri): ?><script src="<?= e(asset('qrcode.min.js')) ?>" defer></script><script src="<?= e(asset('account-totp.js')) ?>" defer></script><?php endif; ?></head>
<body class="app-page<?= $user['role_code'] === 'COACH' ? ' coach-account' : '' ?>" data-totp-policy="<?= e($totpPolicy) ?>">
    <aside class="sidebar">
        <a class="sidebar-brand" href="<?= e(url($user['role_code'] === 'COACH' ? 'rink-app' : 'dashboard')) ?>"><span class="sidebar-brand-mark" aria-hidden="true"><img src="<?= e(asset('cat-logo.png')) ?>" alt=""></span><span class="brand-lockup" aria-label="CanSkate Achievement Tracker">
                <span class="brand-word"><b class="brand-initial">C</b>anSkate</span>
                <span class="brand-word"><b class="brand-initial">A</b>chievement</span>
                <span class="brand-word"><b class="brand-initial">T</b>racker</span>
            </span></a>
        <nav class="primary-nav" aria-label="Main navigation">
            <?php if (is_array($coachNavigator)): ?><?php require __DIR__ . '/partials/coach-rink-navigator.php'; ?><?php endif; ?>
            <?php if (in_array($user['role_code'], ['ADMINISTRATOR', 'REGISTRAR', 'READ_ONLY'], true)): ?><a class="nav-item" href="<?= e(url('dashboard')) ?>">Skaters</a><?php endif; ?>
            <?php if (in_array($user['role_code'], ['ADMINISTRATOR', 'REGISTRAR'], true)): ?><a class="nav-item" href="<?= e(url('sessions')) ?>">Registration</a><?php endif; ?><?php if ($user['role_code'] !== 'COACH'): ?><a class="nav-item" href="<?= e(url('reports')) ?>">Reports</a><a class="nav-item nav-item-rink" href="<?= e(url('rink-app')) ?>">Coach App</a><?php endif; ?>
            <?php if ($user['role_code'] === 'ADMINISTRATOR'): ?><a class="nav-item nav-item-icon-only" href="<?= e(url('admin-tools')) ?>" aria-label="Admin Settings" title="Admin Settings"><span class="nav-icon nav-gear-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9.8 2.8h4.4l.7 2.3c.5.2 1 .5 1.5.9l2.3-.5 2.2 3.8-1.6 1.8v1.8l1.6 1.8-2.2 3.8-2.3-.5c-.5.4-1 .7-1.5.9l-.7 2.3H9.8l-.7-2.3c-.5-.2-1-.5-1.5-.9l-2.3.5-2.2-3.8 1.6-1.8v-1.8L3.1 9.3l2.2-3.8 2.3.5c.5-.4 1-.7 1.5-.9l.7-2.3Z"></path><circle cx="12" cy="12" r="3.1"></circle></svg></span></a><?php endif; ?>
        </nav>
        <div class="sidebar-footer"><a class="avatar account-avatar nav-account-avatar" href="<?= e(url('account')) ?>" title="Manage account for <?= e($displayName) ?>"><?= e($userInitials) ?></a><form method="post" action="<?= e(url('logout')) ?>"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><button class="sign-out" type="submit">Sign out</button></form></div>
    </aside>
    <main class="app-main account-main"><header class="topbar"><div><span class="eyebrow">Personal settings</span><h1>My account</h1><p>Manage your profile, report-card signature, password, and two-factor authentication settings.</p></div></header>
        <?php foreach ($flashes as $flash): ?><div class="alert alert-<?= e($flash['type']) ?> dashboard-alert"><?= e($flash['message']) ?></div><?php endforeach; ?>
        <?php if ($passwordOnly): ?><div class="alert alert-warning account-alert">Your temporary password must be changed before you can continue.</div><?php endif; ?>
        <div class="account-layout">
            <?php if (!$passwordOnly): ?><section class="user-card"><div class="card-heading"><span class="eyebrow">Profile</span><h2><?= e($displayName) ?></h2><p>Your email address is also your sign-in user ID.</p></div><form class="user-form" method="post" action="<?= e(url('account/profile')) ?>"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><div class="form-grid"><label>First name<input name="first_name" value="<?= e($user['first_name'] ?? '') ?>" autocomplete="given-name" required maxlength="100"></label><label>Last name<input name="last_name" value="<?= e($user['last_name'] ?? '') ?>" autocomplete="family-name" required maxlength="100"></label></div><label>Email address<input name="email" type="email" value="<?= e($user['email'] ?: $user['username']) ?>" autocomplete="email" required maxlength="254"></label><button class="button button-primary" type="submit">Save profile</button></form></section><?php endif; ?>
            <section class="user-card password-card"><div class="card-heading"><span class="eyebrow"><?= $passwordOnly ? 'Required action' : 'Security' ?></span><h2>Change password</h2><p>Use at least 12 characters and keep it unique to your CAT account.</p></div><form class="user-form" method="post" action="<?= e(url('account/password')) ?>"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><label>Current password<input name="current_password" type="password" autocomplete="current-password" required></label><div class="form-grid"><label>New password<input name="new_password" type="password" autocomplete="new-password" required minlength="12"></label><label>Confirm new password<input name="new_password_confirmation" type="password" autocomplete="new-password" required minlength="12"></label></div><button class="button button-primary" type="submit">Change password</button></form></section>
            <?php if (!$passwordOnly): ?><section class="user-card totp-card"><div class="card-heading"><span class="eyebrow">Security</span><h2>Authenticator app</h2><p><?= $totpEnabled ? 'Two-factor authentication is enabled for your account.' : 'Add an additional layer of protection to your data using an authenticator-app code to sign in.' ?></p></div><div class="user-form"><?php if ($totpEnabled): ?><form method="post" action="<?= e(url('account/totp/disable')) ?>" class="stacked-form"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><label>Current authenticator code<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required></label><button class="button button-secondary" type="submit">Disable two-factor authentication</button></form><?php elseif (is_string($totpSetupSecret)): ?><p class="totp-setup-copy">Scan this QR code with your authenticator app, then enter its current six-digit code to finish setup.</p><div class="totp-qr" data-totp-qr data-totp-uri="<?= e((string) $totpProvisioningUri) ?>" aria-label="Authenticator app setup QR code"></div><details class="totp-manual-key"><summary>Can’t scan the code?</summary><p>Account: <strong><?= e($user['email'] ?: $user['username']) ?></strong></p><code class="totp-secret"><?= e($totpSetupSecret) ?></code></details><form method="post" action="<?= e(url('account/totp/confirm')) ?>" class="stacked-form"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><label>Enter the current six-digit code<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required autofocus></label><button class="button button-primary" type="submit">Enable two-factor authentication</button></form><form method="post" action="<?= e(url('account/totp/cancel-setup')) ?>" class="totp-cancel-setup"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><button class="button button-ghost" type="submit">Do this later</button></form><?php else: ?><form method="post" action="<?= e(url('account/totp/setup')) ?>"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><button class="button button-secondary" type="submit">Set up authenticator app</button></form><?php endif; ?></div></section><?php endif; ?>
            <?php if (!$passwordOnly): ?>
                <section class="user-card signature-card" id="report-card-signature">
                    <div class="card-heading"><span class="eyebrow">Report cards</span><h2>Your signature</h2><p>Upload the signature that should appear on report cards you generate. Leave blank if you don't want your signature added automatically.</p></div>
                    <div class="signature-preview <?= !empty($signatureMetadata['has_signature']) ? 'has-signature' : '' ?>"><?php if (!empty($signatureMetadata['has_signature'])): ?><img src="<?= e(url('api/account/report-card-signature?v=' . rawurlencode((string) ($signatureMetadata['updated_at'] ?? '')))) ?>" alt="Your saved report-card signature"><?php else: ?><span>No signature uploaded</span><?php endif; ?></div>
                    <form class="user-form signature-upload-form" method="post" action="<?= e(url('account/report-card-signature')) ?>" enctype="multipart/form-data"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="MAX_FILE_SIZE" value="2097152"><label>Signature image<input name="signature_file" type="file" accept="image/png,image/jpeg,image/webp,.png,.jpg,.jpeg,.webp" required><small>For best results, use a 1200 × 300 transparent PNG. JPEG and WebP with a clean white background are also accepted. Maximum 2 MB; 300 × 80 to 4000 × 2000 pixels; wide aspect ratio from 1.5:1 to 12:1. Avoid shadows, ruled paper, and large empty margins.</small></label><button class="button button-primary" type="submit"><?= !empty($signatureMetadata['has_signature']) ? 'Replace signature' : 'Upload signature' ?></button></form>
                    <?php if (!empty($signatureMetadata['has_signature'])): ?><form class="signature-delete-form" method="post" action="<?= e(url('account/report-card-signature/delete')) ?>"><input type="hidden" name="_token" value="<?= e(csrf_token()) ?>"><button class="button button-ghost" type="submit">Remove signature</button></form><?php endif; ?>
                </section>
            <?php endif; ?>
        </div>
    </main>
    <?php require __DIR__ . '/partials/site-footer.php'; ?>
</body>
</html>
